server:
  port: 8889
eureka:
  instance:
    hostname: eureka2
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 3000
spring:
  application:
    name: eureka-server