server:
  port: 8888
eureka:
  instance:
    hostname: eureka
    lease-expiration-duration-in-seconds: 30
    #lease-expiration-duration-in-seconds，表示eureka server至上一次收到client的心跳之后，
    #等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。
    #默认为90秒
    #如果该值太大，则很可能将流量转发过去的时候，该instance已经不存活了。
    #如果该值设置太小了，则instance则很可能因为临时的网络抖动而被摘除掉。
    #该值至少应该大于 lease-renewal-interval-in-seconds:
    lease-renewal-interval-in-seconds: 10
    # lease-renewal-interval-in-seconds:，表示eureka client发送心跳给server端的频率。
    #如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，
    #则将摘除该instance。除此之外，如果该instance实现了HealthCheckCallback，并
    #决定让自己unavailable的话，则该instance也不会接收到流量。

  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/
    registry-fetch-interval-seconds: 30 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
  server:
    enable-self-preservation: false #是否开启自我保护模式，默认为true。
    eviction-interval-timer-in-ms: 3000 #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
spring:
  application:
    name: eureka-server